GET http://localhost/card

###

POST http://localhost/card/set_card_uid
content-type: application/x-www-form-urlencoded

card_uid=549B2822

###

POST http://localhost/auth/register
Content-Type: application/x-www-form-urlencoded

user_name=CotoMKS27
&full_name=Muhammad Chandra Hasan
&email=cn1250425@gmail.com
&password=Chandra1250425
&phone_number=087777777777
&card_uid=549B2822

###

POST http://localhost/auth/login
Content-Type: application/x-www-form-urlencoded

email=nanokaaa@wancommunity.org
&password=kannayama

###

POST http://localhost/auth/register
Content-Type: application/x-www-form-urlencoded

user_name=Nanokaaa
&full_name=Khaidir Muktamar
&email=nanokaaa@wancommunity.org
&password=kannayama
&phone_number=087777777777
&card_uid=549B2822

###